### PR TITLE
Planned coverage of new features in Reactive Hibernate

### PR DESCRIPTION
**Pull request by fedinskiy**
Main issue https://issues.redhat.com/browse/QUARKUS-1079

### CODE REVIEW

**Review by rsvoboda — CHANGES_REQUESTED** [review]
https://in.relation.to/2021/10/13/hibernate-reactive-1_0_0_CR10/
 - automatic schema validation and update for MySQL, Db2 and MS SQL Server
   - check https://github.com/hibernate/hibernate-reactive/pull/1043/files for initial inspiration
 - changed the openSession and openStateless methods for the creation of a new session

https://in.relation.to/2021/10/27/hibernate-reactive-1/
 - test coverage for VertxInstance class - mentioned in https://github.com/hibernate/hibernate-reactive/milestone/13?closed=1 and https://github.com/hibernate/hibernate-reactive/pull/935/files

https://github.com/hibernate/hibernate-reactive/milestone/15?closed=1
 - test case to use Session.setBatchSize()

**Comment by fedinskiy** [comment]
@rsvoboda 
1) "Automatic schema validation and update" is the same as "Generating database schema from the code and updating it". Do you want me to change the wording?
2) Changed methods: this is already covered, since they dropped the old methods.
3) VertxInstance — added.

**Comment by rsvoboda** [comment]
For the first point I miss "validation" part in the original text

**Comment by fedinskiy** [comment]
@rsvoboda first point is now also fixed

**Review by rsvoboda — APPROVED** [review]

**Review by mjurc — APPROVED** [review]

**Pull request merged**
